# Generated by Django 5.0.4 on 2024-04-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0002_alter_song_album_delete_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
