# Generated by Django 5.0.4 on 2024-04-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0004_remove_song_album_remove_song_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
